from telegraf

# setting environment variables
env INFLUXDB_URL=http://influxdb:8086

# adding file to the image
add ./telegraf /var/lib/telegraf
add ./telegraf/telegraf.conf /etc/telegraf/telegraf.conf
