from flink:1.8-scala_2.11

# setting environment variables
env JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
env AWS_ACCESS_KEY_ID=AKIAV3IXPVU7EX5ERHXG
env AWS_SECRET_ACCESS_KEY=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
env AWS_REGION=eu-central-1
env AWS_FORMAT=json

# adding file to the image
add . /flink-analyzer
