version: '2'

networks: 
    custom_network:
        driver: bridge

services:

    zookeeper:
        image: andrealeo93/sdcc-repository:Zookeeper
        container_name: zookeeper
        hostname: zookeeper
        networks: 
            - custom_network
        ports:
            - '2181:2181'
        mem_limit: 2G
        mem_reservation: 1G
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"

    kafka:
        image: andrealeo93/sdcc-repository:Kafka
        container_name: kafka
        hostname: kafka
        networks: 
            - custom_network
        ports:
            - '9092:9092'
        depends_on:
            - zookeeper
        links:
            - zookeeper
        mem_limit: 2G
        mem_reservation: 1G
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
        

    kafka-producer:
        image: andrealeo93/sdcc-repository:Kafka-producer
        container_name: kafka-producer
        hostname: kafka-producer
        networks: 
            - custom_network
        expose:
            - "5005" # remote intellij debug
        ports:
            - "5005:5005" # remote intellij debug
        depends_on:
            - zookeeper
            - kafka
        links:
            - zookeeper
            - kafka
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        mem_limit: 512m
        mem_reservation: 256m
        volumes:
            - "/mnt/sdcc-airmonitoring-data/dataset-sender:/dataset-sender/csv_dataset"
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
        

    influxdb:
        image: andrealeo93/sdcc-repository:Influxdb
        container_name: influxdb
        hostname: influxdb
        networks:
          - custom_network
        expose:
          - "8083"
          - "8086"
        ports:
          - "8086:8086"     #HTTP API port
          - "8083:8083"     #administrator interface port
        mem_limit: 3G
        mem_reservation: 1G
        volumes:
            - "/mnt/sdcc-airmonitoring-data/influxdb:/var/lib/influxdb"
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
        

    telegraf:
        image: andrealeo93/sdcc-repository:Telegraf
        container_name: telegraf
        hostname: telegraf
        networks:
          - custom_network
        expose:
          - "8125"
          - "8092"
          - "8094"
        ports:
          - "8125:8125"
          - "8092:8092"
          - "8094:8094"
        depends_on:
          - influxdb
          - kafka
        links:
          - influxdb
          - kafka
          - zookeeper
        entrypoint: 'bash -c "sleep 20 && telegraf"'
        mem_limit: 2G
        mem_reservation: 1G
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
        

    chronograf:
        image: andrealeo93/sdcc-repository:Chronograf
        container_name: chronograf
        hostname: chronograf
        networks:
            - custom_network
        expose:
            - "8888"
        ports:
            - "8888:8888"
        depends_on:
            - influxdb
        links:
            - influxdb
        mem_limit: 512m
        mem_reservation: 256m
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
        

    flink-jobmanager:
        image: andrealeo93/sdcc-repository:Flink-jobmanager
        hostname: flink-jobmanager
        container_name: flink-jobmanager
        expose:
            - "6123"
            - "5007"
        networks:
            - custom_network
        ports:
            - "8081:8081"
            - "5007:5007"
        command: jobmanager
        links:
            - zookeeper
            - kafka
        environment:
            - AWS_ACCESS_KEY_ID=AKIAV3IXPVU7EX5ERHXG
            - AWS_SECRET_ACCESS_KEY=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
            - AWS_REGION=eu-central-1
            - AWS_FORMAT=json
            - FLINK_JAR=/flink-analyzer/jar/flink-analyzer-1.0-SNAPSHOT.jar
            - FLINK_CLASS=sdcc1819.Query1,sdcc1819.SensorFailure
        mem_limit: 2G
        mem_reservation: 1G
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
        

    flink-taskmanager:
        image: andrealeo93/sdcc-repository:Flink-jobmanager
        hostname: flink-taskmanager
        container_name: flink-taskmanager
        networks:
            - custom_network
        expose:
            - "5006" # remote intellij debug
            - "6121"
            - "6122"
        ports:
            - "5006:5006"  # remote intellij debug
        depends_on:
            - flink-jobmanager
        links:
            - flink-jobmanager
            - zookeeper
            - kafka
        command: taskmanager
        environment:
            - AWS_ACCESS_KEY_ID=AKIAV3IXPVU7EX5ERHXG
            - AWS_SECRET_ACCESS_KEY=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
            - AWS_REGION=eu-central-1
            - AWS_FORMAT=json
        mem_limit: 3G
        mem_reservation: 1G
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
    
    elasticache-proxy:
        image: andrealeo93/sdcc-repository:Elasticache-proxy
        hostname: elasticache-proxy
        container_name: elasticache-proxy
        networks:
            - custom_network
        expose:
            - "3456"
        ports:
            - "3456:3456"  # remote intellij debug
        command: bash
        stdin_open: true
        tty: true
        environment:
            - LOCAL_FORWARD_PORT=3456
            - ELASTICACHE_REMOTE_HOST=elasticache-influxdb.kzez0j.0001.euc1.cache.amazonaws.com
            - ELASTICACHE_REMOTE_PORT=6379
        mem_limit: 512M
        mem_reservation: 256M
        logging: 
            driver: awslogs
            options:
                awslogs-group: "awslogs-air-monitoring-ecs"
                awslogs-region: "eu-central-1"
                awslogs-stream-prefix: "awslogs-air-monitoring"
